apiVersion: batch/v1
kind: Job
metadata:
  name: handson-02
spec:
  template:
    spec:
      containers:
      - name: ml
        image: byrnedo/alpine-curl
        imagePullPolicy: Always
        command: [/bin/sh]
        args:
        - "-c"
        - >
          curl -X POST -H 'Content-type: application/json' --data '{"text": "hello world"}' "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 0

