apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ml-pipeline
spec:
  entrypoint: entry
  onExit: alarm-slack

  ######################################
  # Volumes
  ######################################
  volumeClaimTemplates:
  - metadata:
      name: wf-storage
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: aws-efs

  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: model-storage

  templates:
  ######################################
  # Definitions
  ######################################
  # Exit Handler
  - name: alarm-slack
    container:
      image: byrnedo/alpine-curl
      imagePullPolicy: Always
      command: [/bin/sh]
      args:
      - "-c"
      - >
         curl -X POST -H 'Content-type: application/json' --data '{"text": "Training Done!"}' "https://hooks.slack.com/services/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"

  # Step Definitions
  - name: input
    inputs:
    container:
      imagePullPolicy: Always
      image: 086558720570.dkr.ecr.ap-northeast-2.amazonaws.com/mm/plz
      command: ["python", "input.py"]
      args:
      - "mms-testresult"  
      - "data.npz"  
      - "/wf_storage/data.npz"  
      volumeMounts:
      - mountPath: /model_storage
        name: model-storage
      - mountPath: /wf_storage
        name: wf-storage
      resources:
        limits:
          cpu: 1
          memory: 1Gi
    nodeSelector:
      role: train-cpu

  - name: train
    inputs:
      parameters:
      - name: epoch
      - name: activate
      - name: dropout
      - name: data-path
    container:
      imagePullPolicy: Always
      image: 086558720570.dkr.ecr.ap-northeast-2.amazonaws.com/mm/plz
      command: ["python", "train.py"]
      args:
      - "{{inputs.parameters.epoch}}"
      - "{{inputs.parameters.activate}}"
      - "{{inputs.parameters.dropout}}"
      - "{{inputs.parameters.data-path}}"
      volumeMounts:
      - mountPath: /model_storage
        name: model-storage
      - mountPath: /wf_storage
        name: wf-storage
      resources:
        limits:
          cpu: 1
          memory: 1Gi
    nodeSelector:
      role: train-gpu

  - name: output
    inputs:
    container:
      imagePullPolicy: Always
      image: 086558720570.dkr.ecr.ap-northeast-2.amazonaws.com/mm/plz
      command: ["python", "output.py"]
      args:
      - "mms-testresult"  
      - "/model_storage"  
      volumeMounts:
      - mountPath: /model_storage
        name: model-storage
      - mountPath: /wf_storage
        name: wf-storage
      resources:
        limits:
          cpu: 1
          memory: 1Gi
    nodeSelector:
      role: train-cpu

  ######################################
  # Workflows
  ######################################
  - name: entry
    dag:
      tasks:
      - name: input-A
        template: input
      - name: train-01
        template: train
        arguments:
          parameters:
          - name: epoch
            value: "1"
          - name: activate
            value: "relu"
          - name: dropout
            value: "0.1"
          - name: data-path
            value: "/wf_storage/data.npz"
        dependencies:
          - input-A
      - name: train-02
        template: train
        arguments:
          parameters:
          - name: epoch
            value: "2"
          - name: activate
            value: "tanh"
          - name: dropout
            value: "0.5"
          - name: data-path
            value: "/wf_storage/data.npz"
        dependencies:
          - input-A
      - name: train-03
        template: train
        arguments:
          parameters:
          - name: epoch
            value: "2"
          - name: activate
            value: "linear"
          - name: dropout
            value: "0.5"
          - name: data-path
            value: "/wf_storage/data.npz"
        dependencies:
          - input-A
      - name: output-B
        template: output
        dependencies:
          - train-01
          - train-02
          - train-03
