apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  storageClassName: aws-efs
  mountOptions:
  - vers=4.1
  nfs:
    path: /
    server: {{ .Values.nfsServer }}
  persistentVolumeReclaimPolicy: Delete

